---
- ansible.builtin.set_fact:
    project_dir: "{{ playbook_dir }}/.."
- ansible.builtin.set_fact:
    project_dir: "{{ ansible_user_dir }}/{{ zuul.project.src_dir }}"
  when: zuul is defined
- name: Stat {{ project_dir }}
  ansible.builtin.stat:
    path: "{{ project_dir }}"
  tags:
    - no-cache
  register: src_path
- name: Make sure project_dir is present
  ansible.builtin.assert:
    that:
      - "src_path.stat.isdir"
- name: Check ~/.kube/config
  ansible.builtin.stat:
    path: ~/.kube/config
  register: kube_config_stat
- ansible.builtin.debug:
    var: kube_config_stat
