---
- name: Setup Openshift cluster
  hosts: all
  tasks:
    # https://github.com/packit-service/sandcastle#developing-sandcastle
    - name: Add permissions for service account
      ansible.builtin.command: oc adm policy add-role-to-user edit system:serviceaccount:myproject:default
      become: true
    - name: grant everyone access to {{ item }} so we can use it inside test container
      ansible.builtin.file:
        path: "{{ item }}"
        mode: "0775"
      loop:
        - "~/.kube"
        - "~/.kube/config"
      become: true
